### ISSUE TITLE
AppHelper doesn't exist in cakePHP3

### ISSUE THREAD

**Issue by lorro** [oldskool/cakephp-js#10]
I get errors cake can't load `App\View\Helper\AppHelper;`
In latest cakePHP3 builds there isn't a class AppHelper anymore.

I would suggest you just replace `use App\View\Helper\AppHelper` by `use Cake\View\Helper;` and let your helpers extend Helper instead of AppHelper. Works perfectly fine like that if I make those changes myself.

**Comment by oldskool** [comment]
Thanks for reporting this. Fixed this in 40a2b1259837d058ecdfad7bcb3a0f551770fe7f
