### ISSUE TITLE
cakephp-js error

### ISSUE THREAD

**Issue by kapa3** [oldskool/cakephp-js#11]
[https://ja.stackoverflow.com/questions/33418/]

create table companies (
id int not null primary key auto_increment,
name varchar(255) not null,
created datetime not null,
modified datetime not null
);

create table branches (
id int not null primary key auto_increment,
name varchar(255) not null,
company_id int not null,
modified datetime not null
);

create table prices (
id int not null primary key auto_increment,
discount varchar(250),
company_id int not null,
branch_id int not null,
modified datetime not null
);

bin/cake bake model all
bin/cake bake controller all
bin/cake bake template all

■ src/Template/Layouts/default.ctp
<?= $this->Html->script('jquery-3.1.1.min');
<?= $this->fetch('script') ?>

■ src/Controller/PricesController.php
<?php
App::uses('AppController', 'Controller');

 class PricesController extends AppController { 

    public $helpers = array('Js'=> array('Jquery'));
    public $components = array('RequestHandler', 'Paginator');

public function ajax_ctpdynamic_selects() { 
        $Companies = $this->Price->Company->find('list');
        $this->set('options',
            $this->Price->Branch->find('list',
                array(
                    'conditions' => array(
                        'Branch.company_id' => $this->params['url']['data']['Price']['company_id']
                    ),
                    'fields' => array(
                        'Branch.id',
                        'Branch.name'
                    )
                )
            )
        );
        $this->set(compact('Companies', 'branches'));
}

■ src/Template/Prices/ajax_ctpdynamic_selects.ctp
<?php foreach($options as $key => $val) : ?>
<option value="<?php echo $key; ?>"><?php echo $val; ?></option>
<?php endforeach; ?>

■ src/Template/Prices/add.ctp
<div class="prices form">
        <fieldset>
                <legend><?php echo __('Add Price'); ?></legend>
<?php
        $this->Js->get('#PriceCompanyId')->event(
        'change',
        $this->Js->request(
                array('controller'=>'Prices','action'=>'ajax_ctpdynamic_selects'),
                array('update' => '#PriceBranchId', 'dataExpression' => true, 'data' => 
    '$("#PriceCompanyId").serialize()')
                )
        );
        echo $this->Js->writeBuffer();
?>
   <?php
        echo $this->Form->create('Price');
        echo $this->Form->input('discount');
        echo $this->Form->input('company_id', array('label'=>'カテゴリ', 'empty'=>'選んでください'));
        echo $this->Form->input('branch_id', array('label'=>'アイテム', 'empty'=>'選んでください'));
        echo $this->Form->end(__('Submit'));
   ?>
        </fieldset>
</div>
<div class="actions">
        <h3><?php echo __('Actions'); ?></h3>
        <ul>
                <li><?php echo $this->Html->link(__('List Prices'), array('action' => 'index')); ?>
     </li>
                <li><?php echo $this->Html->link(__('List Companies'), array('controller' =>
     'companies', 'action' => 'index')); ?> 
     </li>
                <li><?php echo $this->Html->link(__('New Company'), array('controller' => 
     'companies', 'action' => 'add')); ?>
</li>
                <li><?php echo $this->Html->link(__('List branches'), array('controller' =>
     'branches', 'action' => 'index')); ?>
     </li>
                <li><?php echo $this->Html->link(__('New Branch'), array('controller' =>
     'branches', 'action' => 'add')); ?>
     </li>
        </ul>
</div>

■ http://192.168.1.10/example/prices/
=================================================
Error:  JsHelper could not be found.
Error:  Create the class JsHelper below in file: src/View/Helper/JsHelper.php

<?php
namespace App\View\Helper;
use Cake\View\Helper;

class JsHelper extends Helper
{
}

**Comment by kapa3** [comment]
[https://ja.stackoverflow.com/questions/33418/]

**Comment by oldskool** [comment]
Please check the [installation guide](https://github.com/oldskool/cakephp-js#installation). You should initialize the helper by using:

```php
public $helpers = ['CakeJs.Js'];
```

In your controller. You are using:

```php
public $helpers = array('Js'=> array('Jquery'));
```

This is the syntax of the old CakePHP 2.x helper, which no longer exists as such.
