### ISSUE TITLE
Composer-issue

### ISSUE THREAD

**Issue by boindil** [oldskool/cakephp-js#5]
composer update results in the following:

[RuntimeException]
  Unable to get primary namespace for package oldskool/cakephp-js.
  Ensure you have added proper 'autoload' section to your plugin's config as
  stated in README on https://github.com/cakephp/plugin-installer

**Comment by boindil** [comment]
Oh come on ... fix this issue its been 27 days since I reported this issue ....

**Comment by oldskool** [comment]
Sorry about that @boindil 
Haven't gotten around to this yet. I'll get it fixed today or tomorrow.

**Comment by oldskool** [comment]
Fixed in https://github.com/oldskool/cakephp-js/pull/6
@boindil Sorry for the delay and thanks for reporting!
